name: fitark
description: A professional fitness and exercise application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_countdown_timer: ^4.1.0

  # UI & Icons
  cupertino_icons: ^1.0.6

  # Animations & Media
  lottie: ^3.1.0

  # Text-to-Speech
  flutter_tts: ^4.0.2

  # State Management
  provider: ^6.1.2

  # Data Persistence
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3+1

  # Local Storage & File System
  path_provider: ^2.1.2

  # Object Equality
  equatable: ^2.0.5

  # Date & Time
  intl: ^0.19.0

  # Device Features
  wakelock_plus: ^1.2.5
  permission_handler: ^11.3.1

  # Audio & Sound
  audioplayers: ^6.0.0
  just_audio: ^0.9.37

  # Notifications
  flutter_local_notifications: ^17.1.2

  # Network & HTTP
  http: ^1.2.1
  dio: ^5.4.3+1

  # Utilities
  path: ^1.8.3
  uuid: ^4.4.0

  # Charts & Analytics
  fl_chart: ^0.68.0

  # Image & File Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Platform Integration
  url_launcher: ^6.2.5
  share_plus: ^7.2.2

  # Forms & Validation
  form_field_validator: ^1.1.0

  # JSON & Serialization
  json_annotation: ^4.8.1

  # Firebase
  firebase_messaging: ^15.0.3
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_functions: ^5.0.3
  firebase_analytics: ^11.2.0
  # Add Google Sign In
  google_sign_in: ^6.1.6

  # Optional Firebase features
  firebase_crashlytics: ^4.3.9 # Crash reporting
  supabase_flutter: ^2.9.1

  # State Management

  # Navigation
  go_router: ^10.0.0

  # HTTP & API

  # Local Storage

  # Location & Maps
  geolocator: ^9.0.0
  google_maps_flutter: ^2.5.0

  # UI & Design
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Build runners for code generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

